enum CursorStyle {
  auto,
  normal, // same as default
  none,
  contextMenu,
  help,
  pointer,
  progress,
  wait,
  cell,
  crosshair,
  text,
  verticalText,
  alias,
  copy,
  move,
  noDrop,
  notAllowed,
  grab,
  grabbing,
  allScroll,
  colResize,
  rowResize,
  nResize,
  eResize,
  sResize,
  wResize,
  neResize,
  nwResize,
  seResize,
  swResize,
  ewResize,
  nsResize,
  newswResize,
  nwseResize,
  zoomIn,
  zoomOut,
}

const cursors = <CursorStyleMap>[
  CursorStyleMap('auto', CursorStyle.auto),
  CursorStyleMap('default', CursorStyle.normal),
  CursorStyleMap('none', CursorStyle.none),
  CursorStyleMap('context-menu', CursorStyle.contextMenu),
  CursorStyleMap('help', CursorStyle.help),
  CursorStyleMap('pointer', CursorStyle.pointer),
  CursorStyleMap('progress', CursorStyle.progress),
  CursorStyleMap('wait', CursorStyle.wait),
  CursorStyleMap('cell', CursorStyle.cell),
  CursorStyleMap('crosshair', CursorStyle.crosshair),
  CursorStyleMap('text', CursorStyle.text),
  CursorStyleMap('vertical-text', CursorStyle.auto),
  CursorStyleMap('alias', CursorStyle.alias),
  CursorStyleMap('copy', CursorStyle.copy),
  CursorStyleMap('move', CursorStyle.move),
  CursorStyleMap('no-drop', CursorStyle.noDrop),
  CursorStyleMap('not-allowed', CursorStyle.notAllowed),
  CursorStyleMap('grab', CursorStyle.grab),
  CursorStyleMap('grabbing', CursorStyle.grabbing),
  CursorStyleMap('all-scroll', CursorStyle.allScroll),
  CursorStyleMap('col-resize', CursorStyle.colResize),
  CursorStyleMap('row-resize', CursorStyle.rowResize),
  CursorStyleMap('n-resize', CursorStyle.nResize),
  CursorStyleMap('e-resize', CursorStyle.eResize),
  CursorStyleMap('s-resize', CursorStyle.sResize),
  CursorStyleMap('w-resize', CursorStyle.wResize),
  CursorStyleMap('ne-resize', CursorStyle.neResize),
  CursorStyleMap('nw-resize', CursorStyle.nwResize),
  CursorStyleMap('se-resize', CursorStyle.seResize),
  CursorStyleMap('sw-resize', CursorStyle.swResize),
  CursorStyleMap('ew-resize', CursorStyle.ewResize),
  CursorStyleMap('ns-resize', CursorStyle.nsResize),
  CursorStyleMap('nesw-resize', CursorStyle.newswResize),
  CursorStyleMap('nwse-resize', CursorStyle.nwseResize),
];

class CursorStyleMap {
  const CursorStyleMap(this.name, this.style);

  final String name;
  final CursorStyle style;
}
